config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"

  devise_for :suckers
  resources :suckers, only: [:show, :new, :create, :edit, :update]

  root to: 'pages#home'
  resources :beasts do
    member do
      resources :bookings, only: [:show, :new, :create, :edit, :update, :destroy] do
        member do
          resources :reviews, only: [:new, :create, :edit, :update, :destroy]
        end
      end
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sucker.rb
class Sucker < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
  has_many :beasts
  has_many :reviews, through: :bookings
end

app/controllers/suckers_controller.rb
class SuckersController < ApplicationController
  before_action :authenticate_sucker!, only: [:edit, :update]
  before_action :set_current_sucker, only: [:show, :edit, :update]
  def new
    @sucker = Sucker.new()
  end

  def create
    @sucker = Sucker.new(sucker_params)
    @sucker.save
  end

  def edit
  end

  def update
    @test_sucker.update(sucker_params)
  end

  def show
    @average_rating = 0
    @count = 0
    @test_sucker.reviews.each do |review|
      if review.sucker_rating
        @count += 1
        @average_rating += review.sucker_rating
      end
    end
    authorize @test_sucker
  end

  private

  def set_current_sucker
    @test_sucker = Sucker.find(params[:id])
  end

  def sucker_params
    params.require(:sucker).permit(:name, :user_name, :passowrd, :email, :phone)
  end
end

app/views/suckers/show.html.erb
<div class="banner-star">
  <h1><%= @test_sucker.name %></h1>
</div>

<div class="container-beast">


  <% if @test_sucker == current_sucker %>
    <h2>Bookings</h2>

    <div class="cards">
      <% @test_sucker.bookings.each do |booking| %>
        <div class="card m-3 p-1" style="width: 100%;">
          <h5 class="card-title"><%= link_to booking.beast.name, beast_path(booking.beast.id) %></h5>
          <div class="card-subtitle mb-2 text-muted">
            <p>From <%= booking.start_date %> <br>
            To <%= booking.end_date %></p>
          </div>
          <% total = (booking.end_date - booking.start_date) * booking.beast.price%>
          <p>You paid $<%= total %>, loser !</p>
          <% if booking.review.beast_content.nil? && booking.review.beast_rating.nil? %>
            <%= link_to "add review", booking_path(booking.id) %>
          <% else %>

            <div class="card-review flex-grow-1">
              <h5><%= booking.review.beast_content %></h5>
              <% unless booking.review.beast_rating.nil? %>
                <% booking.review.beast_rating.times do %>
                  <i class="fas fa-star"></i>
                <% end %>
              <% end %>
              <br><%= link_to "edit review", booking_path(booking.id) %>
            </div>

          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>



  <h2>Beasts</h2>
  <div class="cards d-flex flex-wrap justify-content-around">
    <% @test_sucker.beasts.each do |beast| %>
      <div class="card w-25 m-3 p-3">
        <h5><%= link_to beast.name, beast_path(beast.id) %></h5>
        <p class="text-muted"><%= beast.type.name %></p>
        <p><%= beast.region %></p>
        <p>$<%= beast.price %>/day</p>
        <% if @test_sucker == current_sucker %>
          <%= link_to "edit", edit_beast_path(beast.id) %>
        <% end %>
      </div>
   <% end %>
  </div>

  <% if @test_sucker == current_sucker %>
    <h2>Your Beasts booking history</h2>

    <div class="cards">
      <% @test_sucker.beast_ids.each do |id| %>
        <% @booking = Booking.where(beast_id: id) %>
         <% @booking.each do |booking| %>
          <div class="card m-3 p-1 rounded">

            <h5 class="card-title"><%= link_to booking.beast.name, beast_path(booking.beast.id) %></h5>

            <div class="card-subtitle mb-2 text-muted">
              <p>From <%= booking.start_date %> <br>
              To <%= booking.end_date %></p>
            </div>
            <p>You gained $<%= (booking.end_date - booking.start_date) * booking.beast.price %>, bitch please !</p>
            <% if booking.review.sucker_content.nil? && booking.review.sucker_rating.nil? %>
            <%= link_to "add review", booking_path(booking.id) %>
          <% else %>

            <div class="card-review flex-grow-1">
              <h5><%= booking.review.sucker_content %></h5>
              <% unless booking.review.sucker_rating.nil? %>
                <% booking.review.sucker_rating.times do %>
                  <i class="fas fa-star"></i>
                <% end %>
              <% end %>
              <br><%= link_to "edit review", booking_path(booking.id) %>
            </div>

          <% end %>
          </div>
         <% end %>
      <% end %>
    </div>

  <% end %>

  <h2>Reviews</h2>
  <% if @count.zero? %>
      <p>No ratings given yet.</p>
    <% else %>
      <p>Average rating: </p>
      <% (@average_rating / @count).times do %>
        <i class="fas fa-star"></i>
      <% end %>
      <%= @average_rating.fdiv(@count).round(1) %>
    <% end %>
  <% @test_sucker.reviews.each do |review| %>
    <% if !review.sucker_content.nil? && !review.sucker_rating.nil? %>
      <div class="card-review">
        <p><%= review.booking.beast.sucker.name + " for " +review.booking.beast.name %></p>
        <h5><%= review.sucker_content %></h5>
        <% unless review.sucker_rating.nil? %>
          <% review.sucker_rating.times do %>
            <i class="fas fa-star"></i>
          <% end %>
        <% end %>
      </div>
    <% end %>
  <% end %>


</div>