config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"

  devise_for :suckers
  resources :suckers, only: [:show, :new, :create, :edit, :update]

  root to: 'pages#home'
  resources :beasts do
    member do
      resources :bookings, only: [:show, :new, :create, :edit, :update, :destroy] do
        member do
          resources :reviews, only: [:new, :create, :edit, :update, :destroy]
        end
      end
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :sucker
  belongs_to :beast
  has_one :review
  validates :sucker_id, :beast_id, :start_date, :end_date, presence: true
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_sucker!, only: [:create, :edit, :update, :destroy]
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  def show
    @beast = @booking.beast
    @review = @booking.review
    authorize @booking
  end

  # def new
  #   @booking = Booking.new
  # end

  def create
    @booking = Booking.new(booking_params)
    @booking.beast_id = params[:id]

    @booking.sucker_id = current_sucker.id
    @availabilities = Availability.where(beast_id: @booking.beast_id)
    found = false
    @availabilities.each do |availability|
      if @booking.start_date > availability.start_date && @booking.end_date < availability.end_date
        new_availability = Availability.new(start_date: @booking.end_date, end_date: availability.end_date)
        availability.update(end_date: @booking.start_date)
        new_availability.beast_id = @booking.beast_id
        new_availability.save
        found = true
      end
    end
    if found
      @booking.save
      @review = Review.new()
      @review.booking_id = @booking.id
      @review.save
      redirect_to sucker_path(current_sucker.id)
    else
      redirect_to beast_path(@booking.beast_id)
    end
    authorize @booking
  end

  def edit
    authorize @booking
  end

  def update
    @booking.update(booking_params)
    authorize @booking
  end

  def destroy
    @booking.destroy
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:sucker_id, :beast_id, :start_date, :end_date)
  end
end

app/views/bookings/_form_review.html.erb
<%= simple_form_for([@beast, @booking, @review], html: {class: "form-group form-box"}, :url => review_path)  do |f| %>

<%= "How have they treated your beast?" %> <br>
<%= f.label :sucker_rating %>
<%= f.number_field :sucker_rating, class: "form-control" %> <br>

<%= f.label :sucker_content %>
<%= f.text_field :sucker_content, class: "form-control" %> <br>

<%= f.submit class: "btn btn-primary" %>

<% end %>

app/views/bookings/_form_review_beast.html.erb
<%= simple_form_for([@beast, @booking, @review], html: {class: "form-group form-box"}, :url => review_path)  do |f| %>
<%= "Edit your review on this beast" %> <br>
<%= f.label :beast_rating %>
<%= f.number_field :beast_rating, class: "form-control" %> <br>

<%= f.label :beast_content %>
<%= f.text_field :beast_content, class: "form-control" %> <br>

<%= f.submit class: "btn btn-primary" %>

<% end %>

app/views/bookings/show.html.erb
<% if @booking.sucker_id == current_sucker.id %>
  <%= render 'form_review_beast', beast: @booking.beast, booking: @booking, review: @booking.review %>
<% end %>
<% if current_sucker.id == @beast.sucker_id %>
  <%= render 'form_review', beast: @booking.beast, booking: @booking, review: @booking.review %>
<% end %>