config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"

  devise_for :suckers
  resources :suckers, only: [:show, :new, :create, :edit, :update]

  root to: 'pages#home'
  resources :beasts do
    member do
      resources :bookings, only: [:show, :new, :create, :edit, :update, :destroy] do
        member do
          resources :reviews, only: [:new, :create, :edit, :update, :destroy]
        end
      end
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <!-- <a class="navbar-brand" href="#">BnB</a> -->
  <%= link_to "BnB", root_path, :class => "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <!-- <a class="nav-link" href="#">Find a beast!</a> -->
        <%= link_to "Find a beast!", beasts_path, :class => "nav-link" %>
      </li>
    </ul>
    <div class="right">
      <% if sucker_signed_in? %>

        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "Register a beast!", new_beast_path, :class => "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <img src="https://www.petmd.com/sites/default/files/small-kitten-walking-towards_127900829_0.jpg" alt="" class="avatar">
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", sucker_path(current_sucker.id), :class => "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to "Log out", destroy_sucker_session_path, method: :delete, :class => "dropdown-item" %>
            </div>
          </li>
        </ul>


      <% else %>

        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <!-- <a class="nav-link" href="#">Sign Up<span class="sr-only">(current)</span></a> -->
            <%= link_to "Sign Up", new_sucker_registration_path, :class => "nav-link" %>
          </li>
          <li class="nav-item">
            <!-- <a class="nav-link" href="#">Log In</a> -->
            <%= link_to "Log In", new_sucker_session_path, :class => "nav-link" %>
          </li>
        </ul>
      <% end %>
    </div>
  </div>
</nav>